export default {
  translation: {
    loginForm: {
      name: 'Ваш ник',
      password: 'Пароль',
      registration: 'Регистрация',
      submit: 'Войти',
      hexletChat: 'Hexlet Chat',
      unauthorized: 'Неверные имя пользователя или пароль',
    },
    signupForm: {
      name: 'Имя пользователя',
      password: 'Пароль',
      confirmation: 'Подтведите пароль',
      submit: 'Войти',
      hexletChat: 'Hexlet Chat',
      existError: 'Этот пользователь уже существует',
      requiredFieldError: 'Это обязатаельное поле',
      usernameError: 'От 3 до 20 символов',
      passwordMinError: 'Не менее 6 символов',
      confirmError: 'Пароли должны совпадать',
      ObsceneError: 'Нецензурное слово',
    },
    chatForm: {
      channels: 'Каналы',
      channel: 'Канал',
      send: 'Отправить',
      rename: 'Переименовать',
      delete: 'Удалить',
      deleteQuestion: 'Вы точно хотите удалить канал?',
      yes: 'да',
      no: 'нет',
      logOut: 'Выйти',
      name: 'Имя',
      submit: 'Подтвердить',
      channelExistError: 'Этот канал уже сущестует',
      requiredFieldError: 'Это обязатаельное поле',
      nameMinError: 'Имя должно содержать не менее 3 символов',
      nameMaxError: 'Имя должно содержать не более 20 символов',
      deletedChannelToast: 'Канал удален',
      createdChannelToast: 'Канал создан',
      renaimedChannelToast: 'Канал переименован',
      networkErrorToast: 'Ошибка сети:',
      ObsceneError: 'Нецензурное слово',
      changeChannel: 'Управление каналом',
    },
  },
}
